---

- name: install package certbot
  apt:
    name: certbot
    state: present

- name: add the group ansible_common_remote_group
  group:
    name: ansible_common_remote_group
    state: present

- name: add the user kubeadmin
  user:
    name: kubeadmin
    shell: /bin/bash
    groups: ansible_common_remote_group
    append: yes

- name: create openebs storage class hostpath
  file:
    path: "{{ k8s.openebs.storageclass.hostpath }}"
    state: directory
    mode: '0755'    
