---

- include_tasks: "nodes/install-init.yml"
  when: node_type == "single-master" or node_type == "multi-master" or node_type == "join-master"

- include_tasks: "nodes/install-master-node-single.yml"
  when: node_type == "single-master" 

- include_tasks: "nodes/install-master-node-multi.yml"
  when: node_type == "multi-master" 

- include_tasks: "nodes/install-join-master-node-token.yml"
  when: node_type == "multi-master" 

- include_tasks: "nodes/install-join-master-node.yml"
  when: node_type == "join-master" 

- include_tasks: "nodes/install-join-worker-node-token.yml"
  when: node_type == "single-master" or node_type == "multi-master"

- include_tasks: "nodes/install-worker-node.yml"
  when: node_type == "worker" 
