---
    # file: roles/k8s_admin/tasks/delete-openvpn.yml

    - name: remove file /etc/sysctl.d/openvpn.conf
      file:
        path: /etc/sysctl.d/openvpn.conf
        state: absent
  
    - name: sysctl --system
      shell: sysctl --system
        
    - name: rm directory /etc/openvpn 
      file:
        path: /etc/openvpn 
        state: absent
        
    - name: remove iptables for openvpn
      shell: |
        # allow connection on the openvpn port
        iptables -D INPUT -i {{ openvpn.iface }} -m state --state NEW -p {{ openvpn.proto }} --dport {{ openvpn.port }} -j ACCEPT
        # allow TUN interface connections
        iptables -D INPUT -i tun+ -j ACCEPT
        # allow TUN interface connections to be forwarded through network routing interface
        iptables -D FORWARD -i tun+ -j ACCEPT
        iptables -D FORWARD -i tun+ -o {{ openvpn.network_route_iface }} -m state --state RELATED,ESTABLISHED -j ACCEPT
        iptables -D FORWARD -i {{ openvpn.network_route_iface }} -o tun+ -m state --state RELATED,ESTABLISHED -j ACCEPT
        # NAT the VPN client traffic to the network routing interface
        iptables -t nat -D POSTROUTING -s {{ openvpn.server_ip }}/24 -o {{ openvpn.network_route_iface }} -j MASQUERADE
        # allow TUN interface output connections 
        iptables -D OUTPUT -o tun+ -j ACCEPT
        # save firewall rules (will be run automatically run at boot with iptables-persistent package)
        iptables-save > /etc/iptables/rules.v4

    - name: remove the package "openvpn, openssl, easy-rsa"
      apt:
        pkg: 
        - openvpn
        - openssl 
        - easy-rsa
        state: absent
