---
# see https://metallb.universe.tf/installation/

- name: install metallb load balancer
  shell: |
    kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e "s/strictARP: false/strictARP: true/" | kubectl apply -f - -n kube-system
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/{{ k8s.core.metallb.version }}/config/manifests/metallb-native.yaml
  become: true
  become_user: kubeadmin

- name: install metallb load balancer - wait for
  shell: |
    kubectl wait --namespace metallb-system --for=condition=ready pod --selector=component=controller --timeout=360s
  become: true
  become_user: kubeadmin

- name: create directory /home/kubeadmin/metallb
  file:
    path: /home/kubeadmin/metallb
    state: directory
  become: true
  become_user: kubeadmin

- name: create file /home/kubeadmin/metallb/pool.yaml
  copy:
    content: |      
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: first-pool
        namespace: metallb-system
      spec:
        addresses:
        - {{ k8s.core.metallb.ip_range }}
    dest: /home/kubeadmin/metallb/pool.yaml
  become: true
  become_user: kubeadmin

- name: apply metallb load balancer pool configuration
  shell: kubectl apply -f /home/kubeadmin/metallb/pool.yaml
  become: true
  become_user: kubeadmin

- name: create file /home/kubeadmin/metallb/advert.yaml
  copy:
    content: |
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: first-advert
        namespace: metallb-system
    dest: /home/kubeadmin/metallb/advert.yaml
  become: true
  become_user: kubeadmin

- name: apply metallb load balancer L2 advert configuration
  shell: kubectl apply -f /home/kubeadmin/metallb/advert.yaml
  become: true
  become_user: kubeadmin