---
# see https://openebs.io/docs/quickstart-guide/installation

- name: install package helm
  apt:
    pkg: helm
  when: ansible_facts['os_family'] == "Debian"

- name: install openebs
  shell: |
    helm repo add openebs https://openebs.github.io/openebs
    helm repo update
    helm install openebs --namespace openebs openebs/openebs --create-namespace
  become: true
  become_user: kubeadmin

- name: create directory /home/kubeadmin/openebs
  file:
    path: /home/kubeadmin/openebs
    state: directory
  become: true
  become_user: kubeadmin

- name: create file /home/kubeadmin/openebs/storageclass.yaml
  copy:
    content: |
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-hostpath
        annotations:
          openebs.io/cas-type: local
          cas.openebs.io/config: |
            - name: StorageType
              value: hostpath
            - name: BasePath
              value: {{ k8s.cns.hostpath }}
      provisioner: openebs.io/local
      reclaimPolicy: Delete
      volumeBindingMode: WaitForFirstConsumer
    dest: /home/kubeadmin/openebs/storageclass.yaml
  become: true
  become_user: kubeadmin

- name: kubectl apply -f /home/kubeadmin/openebs/storageclass.yaml
  shell: kubectl apply -f /home/kubeadmin/openebs/storageclass.yaml
  become: true
  become_user: kubeadmin
