---

- name: create directory /home/kubeadmin/netpol
  file:
    path: /home/kubeadmin/netpol
    state: directory
  become: true
  become_user: kubeadmin

- name: create file /home/kubeadmin/netpol/coredns-netpol.yaml
  copy:
    content: |
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: coredns
      spec:
        podSelector: {}
        policyTypes:
          - Egress
        egress:
          - to:
              - namespaceSelector: {}
                podSelector:
                  matchLabels:
                    k8s-app: kube-dns
            ports:
              - port: 53
                protocol: UDP
    dest: /home/kubeadmin/netpol/coredns-netpol.yaml
  become: true
  become_user: kubeadmin

- name: kubectl apply -f /home/kubeadmin/netpol/coredns-netpol.yaml
  shell: kubectl apply -f /home/kubeadmin/netpol/coredns-netpol.yaml
  become: true
  become_user: kubeadmin

