---
# file: roles/k8s_master_nodes/tasks/join.yml

- name: store kubeadm join command for master
  copy:
    src: "{{ all.fetch_directory }}/k8s_join_master_file_{{ all.environment }}"
    dest: "/var/log/k8s_join_master_file_{{ all.environment }}"
  
- name: get kubadm join command for master
  shell: "cat /var/log/k8s_join_master_file_{{ all.environment }}"
  register: kubeadm_join_master_result
  
- name: kubeadm join master
  shell: "{{ kubeadm_join_master_result.stdout }} --cri-socket {{ k8s.cri.criSocket }} --apiserver-advertise-address {{ ansible_host }} {{ k8s.master.kubeadm_extra }} > /var/log/kubeadm_join.log"

- name: create /home/kubeadmin/.kube
  file:
    path: /home/kubeadmin/.kube
    state: directory
    mode: '0755'

- name: remove /home/kubeadmin/.kube/config if exists
  file:
    path: /home/kubeadmin/.kube/config
    state: absent

- name: cp -i /etc/kubernetes/admin.conf /home/kubeadmin/.kube/config
  shell: |
    cp -i /etc/kubernetes/admin.conf /home/kubeadmin/.kube/config
    chown -R kubeadmin:kubeadmin /home/kubeadmin


  