---
# file: roles/k8s_reset/tasks/main.yml

- name: kubeadm reset -f
  shell: kubeadm reset -f
  tags: reset
  when: reset

- name: remove /etc/cni/net.d if exists
  file:
    path: /etc/cni/net.d
    state: absent
  when: reset

- name: remove /var/lib/cni if exists
  file:
    path: /var/lib/cni
    state: absent
  when: reset

- name: remove /var/lib/calico if exists
  file:
    path: /var/lib/calico
    state: absent
  when: reset

- name: remove /var/lib/weave if exists
  file:
    path: /var/lib/weave
    state: absent
  when: reset

#- name: delete (weave|vxlan|vethwe|tun) interfaces if exists
#  shell: |
#      ip link list|cut -f2 -d:|cut -f1 -d@|egrep '(weave)' | xargs ip link delete
#      ip link list|cut -f2 -d:|cut -f1 -d@|egrep '(vxlan)' | xargs ip link delete
#      ip link list|cut -f2 -d:|cut -f1 -d@|egrep '(vethwe-datapath)' | xargs ip link delete
#  ignore_errors: true
#  when: reset

- name: remove openebs storage class hostpath if exists
  file:
    path: "{{ k8s.openebs.storageclass.hostpath }}"
    state: absent
  when: reset

- name: reboot the host
  reboot:
  when: reset
