---
# file: roles/k8s_admin/tasks/install.yml

- include_tasks: "install-haproxy.yml"
  when: task == "haproxy" or task == "all"

- include_tasks: "install-bind.yml"
  when: task == "bind" or task == "all"

- include_tasks: "install-openvpn.yml"
  when: task == "openvpn" or task == "all"

- include_tasks: "install-others.yml"
  when: task == "others" or task == "all"
