---
# file: roles/common/tasks/main.yml

- name: hostnamectl set-hostname 
  shell: |
    hostnamectl set-hostname {{ inventory_hostname }}

- name: remove 127.0.1.1 line from /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    state: absent

- name: add hostname -i line in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_host }} {{ inventory_hostname }}"
    state: present

- name: create directory /etc/iptables
  file:
    path: /etc/iptables
    state: directory
    mode: '0755'

- name: disable ipv6
  shell: |
    echo 'net.ipv6.conf.all.disable_ipv6 = 1' > /etc/sysctl.d/90-disable-ipv6.conf
    sysctl -p -f /etc/sysctl.d/90-disable-ipv6.conf

- name: increase the conntrack table
  shell: |
    sysctl -w net.netfilter.nf_conntrack_max=1000000
    echo "net.netfilter.nf_conntrack_max=1000000" >> /etc/sysctl.conf

- name: install common base packages
  apt:
    pkg: 
    - net-tools
    - golang-cfssl
    - iptables-persistent
    - software-properties-common
    - gpg
    - curl
    - open-iscsi
  when: ansible_facts['os_family'] == "Debian"

- name: Remove "network-manager" package
  apt:
    name: network-manager
    state: absent
  when: ansible_facts['os_family'] == "Debian"

- name: create file /etc/sysctl.d/90-kubelet.conf
  copy:
    content: |
      vm.overcommit_memory=1
      vm.panic_on_oom=0
      kernel.panic=10
      kernel.panic_on_oops=1
      kernel.keys.root_maxbytes=25000000
    dest: /etc/sysctl.d/90-kubelet.conf

- name: sysctl -p /etc/sysctl.d/90-kubelet.conf
  shell: |
    sysctl -p /etc/sysctl.d/90-kubelet.conf

- name: systemctl enable --now iscsid
  shell: |
    systemctl enable --now iscsid

