---

- name: modprobe br_netfilter & sysctl
  shell: |
    modprobe br_netfilter
    sysctl net.bridge.bridge-nf-call-iptables=1
    sysctl net.bridge.bridge-nf-call-ip6tables=1
    sysctl net.ipv4.ip_forward=1

- name: create file /etc/sysctl.d/k8s.conf
  copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/k8s.conf
  become: true

- name: sysctl --system
  shell: sysctl --system

- name: update-alternatives --set iptables, ip6tables, arptables, ebtables
  shell: |
    update-alternatives --set iptables /usr/sbin/iptables-legacy
    update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
    update-alternatives --set arptables /usr/sbin/arptables-legacy
    update-alternatives --set ebtables /usr/sbin/ebtables-legacy

- name: apt-mark unhold kubernetes packages
  shell: | 
    apt-mark unhold kubelet kubeadm kubectl
  when: ansible_facts['os_family'] == "Debian"

- name: install kubernetes packages
  apt:
    pkg:
    - kubelet
    - kubeadm
    - kubectl
  when: ansible_facts['os_family'] == "Debian"

- name: apt-mark hold kubernetes packages
  shell: apt-mark hold kubelet kubeadm kubectl

- name: remove swap from /etc/fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: ' swap '

- name: disable swap
  shell: swapoff -a

