---

- name: remove other cri packages "docker-engine docker.io runc containerd.io cri-o cri-o-runc"
  apt:
    pkg:
    - docker-engine
    - docker.io
    - runc
    - cri-o
    - cri-o-runc
    state: absent
  when: ansible_facts['os_family'] == "Debian"

- name: create file /etc/modules-load.d/containerd.conf
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf

- name: modprobe overlay br_netfilter
  shell: |
    sudo modprobe overlay
    sudo modprobe br_netfilter

- name: install the package containerd.io
  apt:
    pkg:
    - containerd.io
  when: ansible_facts['os_family'] == "Debian"

- name: create directory /etc/containerd
  file:
    path: /etc/containerd
    state: directory

- name: load config default to /etc/containerd/config.toml
  shell: containerd config default | sudo tee /etc/containerd/config.toml

#- name: set SystemdCgroup = true in /etc/containerd/config.toml
#  lineinfile:
#    dest: /etc/containerd/config.toml
#    insertafter: '(\s+)\[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options\](\s+.*)?$'
#    line: '            SystemdCgroup = true'

- name: set SystemdCgroup = true in /etc/containerd/config.toml
  replace: 
    path: /etc/containerd/config.toml
    regexp: '^(.+)SystemdCgroup = false$'
    replace: '\1SystemdCgroup = true'
    backup: yes

#-- name: add endpoint to plugin "cri" in /etc/containerd/config.toml
#  lineinfile:
#    dest: /etc/containerd/config.toml
#    insertafter: '(\s+)\[plugins."io.containerd.grpc.v1.cri".containerd\](\s+.*)?$'
#    line: '      endpoint = "{{ k8s.cri.criSocket }}"'

- name: restart service containerd
  service:
    name: containerd
    state: restarted
