---

- name: remove other cri packages
  apt:
    pkg:
    - docker-engine 
    - docker.io 
    - containerd 
    - runc
    - containerd.io
    state: absent
  when: ansible_facts['os_family'] == "Debian"

- name: install cri-o package
  apt:
    pkg:
    - cri-o
  when: ansible_facts['os_family'] == "Debian"

- name: enable service crio
  service:
    name: crio
    enabled: yes

- name: restart service crio
  service:
    name: crio
    state: restarted
   