---

- name: remove other cri packages "docker-engine docker.io containerd runc containerd.io"
  apt:
    pkg:
    - docker-engine 
    - docker.io 
    - containerd 
    - runc
    - containerd.io
    state: absent
  when: ansible_facts['os_family'] == "Debian"

- name: install packages "cri-o"
  apt:
    pkg:
    - cri-o
  when: ansible_facts['os_family'] == "Debian"

- name: enable service crio
  service:
    name: crio
    enabled: yes

- name: restart service crio
  service:
    name: crio
    state: restarted
   