
all:
  fetch_directory: /tmp
  environment: demo.lv

k8s:
  apt:
    version: v1.31
  cluster:
    configuration: 
      etcd: |
        etcd:
          external:
            endpoints:
              - https://192.168.20.52:2379
              - https://192.168.20.55:2379
              - https://192.168.20.67:2379
            caFile: /etc/etcd/ca.pem
            certFile: /etc/etcd/etcd.pem
            keyFile: /etc/etcd/etcd-key.pem
  registry:
    external: True
    name: flowers.registry
    login: flowers
    password: PssPss2023
    address: 192.168.20.141 
  cri:
    vendor: containerd # cri-o, containerd
    criSocket: unix:///var/run/containerd/containerd.sock
    crio:
      version: v1.31
  master:
    pod_network_cidr: 10.244.0.0/16   
    kubeadm_extra: "--v=99"
    load_balancer_ip: 192.168.20.141
    apiserver_port: 6443
    untaint: false
    untaint_master_nodes:
      - lisboa.europe

  cns:
    hostpath: /data_storage/cns

  coredns:
    namespace: coredns-europe
    port: 53
    zone_name: europe
    external_ip: 192.168.20.180
    forward: 8.8.8.8 8.8.4.4

    zone: |
      europe.               IN  SOA ns1.europe. root.europe. 2015082541 7200 3600 1209600 3600
      europe.               IN  NS  ns1.europe.
      ns1                   IN  A   192.168.20.180

      dashboard.lv.k8s      IN  A   192.168.20.180

  core:
    cni: 
      vendor: calico # calico, weave, flannel, cilium
      cilium:
        version: 1.16.1
      calico:
        version: v3.28.1
      weave:
        version: v2.8.1
      flannel:
        version: latest

    metallb:
      ip_range: "192.168.20.180-192.168.20.189"
      version: v0.14.8
    
    nginx:
      version: v1.11.2

    cert_manager:
      version: v1.15.3
      namespace: cert-manager
      ca:
        cn: "k8s europe CA"
        csr:
          C: France
          L: Paris
          ST: Ile de France
        expiry: 43830h
        renewBefore: 360h

    dashboard:
      csr_CN: dashboard.lv.k8s.europe
      host: dashboard.lv.k8s.europe
      version: v2.7.0
      
    coredns: 
      domain: k8s.europe
      port: 53
      forward: 192.168.20.180

