# harbor configuration

harbor:
  version: v2.8.1
  ca:
    cn: "harbor europe CA"
    csr:
      C: France
      L: Paris
      O: Europe
      ST: Ile de France
    expiry: 43830h
  hostname: 192.168.20.141

# haproxy configuration

haproxy:
  iface: eth1
  iptables:
    port: 6443
  conf: |
    global
    	log /dev/log	local0
    	log /dev/log	local1 notice
    	chroot /var/lib/haproxy
    	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    	stats timeout 30s
    	user haproxy
    	group haproxy
    	daemon

    	ca-base /etc/ssl/certs
    	crt-base /etc/ssl/private

    	ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
    	ssl-default-bind-options no-sslv3

    defaults
    	log	global
    	mode	http
    	option	httplog
    	option	dontlognull
            timeout connect 5000
            timeout client  50000
            timeout server  50000
    	errorfile 400 /etc/haproxy/errors/400.http
    	errorfile 403 /etc/haproxy/errors/403.http
    	errorfile 408 /etc/haproxy/errors/408.http
    	errorfile 500 /etc/haproxy/errors/500.http
    	errorfile 502 /etc/haproxy/errors/502.http
    	errorfile 503 /etc/haproxy/errors/503.http
    	errorfile 504 /etc/haproxy/errors/504.http

    frontend kubernetes
    bind 192.168.20.141:6443
    option tcplog
    mode tcp
    default_backend k8s-master-nodes

    backend k8s-master-nodes
    mode tcp
    balance roundrobin
    option tcp-check
    server k8s-master-0 192.168.20.52:6443 check fall 3 rise 2
    server k8s-master-1 192.168.20.55:6443 check fall 3 rise 2
    server k8s-master-2 192.168.20.67:6443 check fall 3 rise 2

# bind configuration

bind:
  acl_trusted: "192.168.20.0/24; 10.8.0.0/24;"
  forwarders: "8.8.8.8; 8.8.4.4;"
  listen_ip: "192.168.20.141"  
  port: 53
  zone_name: europe
  zone: |
      @   IN  SOA     ns1.europe. root.europe. (
              2011071001  ;Serial
              3600        ;Refresh
              1800        ;Retry
              604800      ;Expire
              86400       ;Minimum TTL
      )
      @       IN  NS          ns1.europe.
      @       IN  A           192.168.20.141
      @       IN  A           192.168.20.52
      @       IN  A           192.168.20.55
      @       IN  A           192.168.20.67
      @       IN  A           192.168.20.91
      @       IN  A           192.168.20.92
      @       IN  A           192.168.20.93
      ns1             IN  A   192.168.20.141
      strasbourg      IN  A   192.168.20.141
      paris           IN  A   192.168.20.52
      roma            IN  A   192.168.20.55
      madrid          IN  A   192.168.20.67
      lisboa          IN  A   192.168.20.91
      madrid          IN  A   192.168.20.92
      amsterdam       IN  A   192.168.20.93
      dashboard.k8s   IN  A   192.168.20.190

# onpenvpn configuration

openvpn:
  listen_ip: "192.168.20.141"
  port: 1194
  proto: tcp
  iface: "eth0"
  server_ip: "10.8.0.0"
  dns: "192.168.20.141"
  network_route: "192.168.20.0"
  network_route_iface: "eth1"
  network_route_delete: "192.168.20.0/24"
  easyrsa_vars: |
      export KEY_COUNTRY="EU"
      export KEY_PROVINCE="France"
      export KEY_CITY="Paris"
      export KEY_ORG="europe"
      export KEY_EMAIL="admin@europe"
      export KEY_OU="OpenVPN"
      export EASYRSA_BATCH="1"

