---
# file: roles/k8s_core/tasks/install-metallb.yml

- name: install metallb load balancer
  shell: |
    kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e "s/strictARP: false/strictARP: true/" | kubectl apply -f - -n kube-system
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/{{ k8s.core.metallb.version }}/config/manifests/metallb-native.yaml
    kubectl wait pods -n metallb-system --all --for condition=Ready --timeout=120s
  become: true
  become_user: kubeadmin

- name: create directory /home/kubeadmin/metallb
  file:
    path: /home/kubeadmin/metallb
    state: directory
  become: true
  become_user: kubeadmin

- name: create file /home/kubeadmin/metallb/config.yaml
  copy:
    content: |
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: {{ k8s.core.metallb.name }}
        namespace: metallb-system
      spec:
        addresses:
        - {{ k8s.core.metallb.addresses }}
      ---
      apiVersion: metallb.io/v1beta1
      kind: BGPAdvertisement
      metadata:
        name: external
        namespace: metallb-system
      spec:
        ipAddressPools:
        - {{ k8s.core.metallb.name }}

    dest: /home/kubeadmin/metallb/config.yaml
  become: true
  become_user: kubeadmin

- name: apply metallb lconfiguration
  shell: kubectl apply -f /home/kubeadmin/metallb/config.yaml
  become: true
  become_user: kubeadmin
