---
# file: roles/k8s_core/tasks/install-cni.yml

- name: install CNI "weave"
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  become: true
  become_user: kubeadmin
  when: k8s.core.cni.vendor == "weave"

- name: install CNI "flannel"
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  become: true
  become_user: kubeadmin
  when: k8s.core.cni.vendor == "flannel"

- name: install CNI "calico"
  file:
    path: /home/kubeadmin/calico
    state: directory
  become: true
  become_user: kubeadmin
  when: k8s.core.cni.vendor == "calico"

- name: install CNI "calico"
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ k8s.core.cni.calico.version }}/manifests/custom-resources.yaml
    kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ k8s.core.cni.calico.version }}/manifests/custom-resources.yaml
    curl -o /home/kubeadmin/calico/calico.yaml -O -L "https://raw.githubusercontent.com/projectcalico/calico/{{ k8s.core.cni.calico.version }}/manifests/calico.yaml"
    kubectl apply -f /home/kubeadmin/calico/calico.yaml
  become: true
  become_user: kubeadmin
  when: k8s.core.cni.vendor == "calico"

- name: install CNI "calicoctl" on kubernetes API datastore
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ k8s.core.cni.calico.version }}/manifests/calicoctl.yaml
#    kubectl exec -ti -n kube-system calicoctl -- /calicoctl get profiles -o wide
  become: true
  become_user: kubeadmin
  when: k8s.core.cni.vendor == "calico"
