---
# file: roles/k8s_core/tasks/install-nginx.yml

- name: install nginx ingress controller
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.0.4/deploy/static/provider/cloud/deploy.yaml
    kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=120s
    kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
  become: true
  become_user: kubeadmin

