---

- name: remove other cri packages
  apt:
    pkg:
    - docker-engine
    - docker.io
    - runc
    - cri-o
    - cri-o-runc
    state: absent
  when: ansible_facts['os_family'] == "Debian"

- name: create file /etc/modules-load.d/containerd.conf
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf

- name: modprobe overlay br_netfilter
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: install containerd.io package
  apt:
    pkg:
    - containerd.io
  when: ansible_facts['os_family'] == "Debian"

- name: create directory /etc/containerd
  file:
    path: /etc/containerd
    state: directory

- name: load config default to /etc/containerd/config.toml
  shell: containerd config default | sudo tee /etc/containerd/config.toml

- name: set SystemdCgroup = true in /etc/containerd/config.toml
  replace: 
    path: /etc/containerd/config.toml
    regexp: '^(.+)SystemdCgroup = false$'
    replace: '\1SystemdCgroup = true'
    backup: yes

- name: restart service containerd
  service:
    name: containerd
    state: restarted
